### ISSUE TITLE
Properties are being ignored on updateAspects when CMIS version is 1.1

### ISSUE THREAD

**Issue by juliomelo** [Alfresco/opencmis-extension#3]
The method updateAspects from AlfrescoUtils does not use properties argument when cmis version is 1.1. Therefore, no properties for the updated aspect is sent to server.

https://github.com/Alfresco/opencmis-extension/blob/61c3aea7726dbe09ad21831d7b577934c8e482d6/src/main/java/org/alfresco/cmis/client/impl/AlfrescoUtils.java#L366-L422

https://github.com/Alfresco/opencmis-extension/blob/61c3aea7726dbe09ad21831d7b577934c8e482d6/src/main/java/org/alfresco/cmis/client/impl/AlfrescoUtils.java#L417-L421

See above that only PropertyIds.SECONDARY_OBJECT_TYPE_IDS is sent.

Also, cmisProperties variable initializing is meaningless, because it is overwritten before any read.

https://github.com/Alfresco/opencmis-extension/blob/61c3aea7726dbe09ad21831d7b577934c8e482d6/src/main/java/org/alfresco/cmis/client/impl/AlfrescoUtils.java#L374

https://github.com/Alfresco/opencmis-extension/blob/61c3aea7726dbe09ad21831d7b577934c8e482d6/src/main/java/org/alfresco/cmis/client/impl/AlfrescoUtils.java#L420

**Comment by killerboot** [comment]
Hi, thanks for raising this.
These concerns will be tracked in https://issues.alfresco.com/jira/browse/REPO-4367

**Comment by jottley** [comment]
This is appears to have been fixed in the above linked JIRA.
