### ISSUE TITLE
alfresco-opencmis-extension-1.1 is currently not available in Maven central repository

### ISSUE THREAD

**Issue by natmuruga** [Alfresco/opencmis-extension#5]
alfresco-opencmis-extension-1.1 is used in one of my projects. As this is currently not available in Maven central repository. Could someone publish this in Maven Central repository that would help us to use in our project.

**Comment by murugacw1** [comment]
Hi All,

Can someone help us to make 1.1 available in maven central. It is really a blocker for us.

Thanks,
Muruga

**Comment by PunchedChimera** [comment]
Hi, thank you for raising this.
These concerns will be tracked in [ALF-22132](https://issues.alfresco.com/jira/browse/ALF-22132 )
These artefacts are currently available on our public repository and the following will provide instructions on how to access: https://docs.alfresco.com/4.1/concepts/opencmis-ext-maven.html

**Comment by natmuruga** [comment]
Thanks a lot David. I really appreciate your response.

Also, If possible, could you please let me know the timeline normally takes
to update to update to maven central

Thanks,
Muruga

**Comment by jottley** [comment]
There currently is no plan to sync this maven central.  As stated above the artifact, and newer versions, are available in the alfresco maven repository. https://artifacts.alfresco.com/nexus/service/rest/repository/browse/public/org/alfresco/cmis/client/alfresco-opencmis-extension/
